/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.javasync.idioms;

import org.junit.Test;

import java.io.IOException;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.stream.Stream;

import static java.lang.System.out;
import static java.time.LocalDate.parse;
import static org.javasync.idioms.Resources.DISCOURSE_ON_THE_METHOD;
import static org.javasync.idioms.Resources.DIVINE_COMEDY;
import static org.javasync.idioms.Resources.METAMORPHOSIS;
import static org.junit.Assert.assertEquals;

public class WeatherWebApiTest {
    @Test public void testPastWeatherAsync() throws IOException {
        CompletableFuture<List<WeatherInfo>> cf = WeatherWebApi
            .pastWeather(37.017, -7.933, parse("2019-04-01"), parse("2019-04-30"));
        cf
            .thenAccept(wis -> wis.stream().findFirst().ifPresent(out::println))
            .join();
        cf
            .thenApply(wis -> wis.stream().mapToInt(WeatherInfo::getTempC).max())
            .thenAccept(temp -> temp.ifPresent(out::println))
            .join();

    }
}
