/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.javasync.idioms;

import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.assertEquals;

public class PersonTest {
    @Test public void testCarInsuranceName() throws IOException {
        Person p = new Person();
        assertEquals("Unknown", p.getCarInsuranceName());
    }
}
